# Generated by Django 4.0.3 on 2022-04-14 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('D', 'Design'), ('VE', 'Video Edition')],
                                              default='D', max_length=2)),
                ('delivery_due', models.DateTimeField()),
                ('price', models.FloatField()),
                ('private', models.BooleanField(default=False)),
                ('status', models.CharField(default='WA', max_length=2)),
                ('professional', models.ForeignKey(blank=True, null=True,
                                                   on_delete=django.db.models.deletion.DO_NOTHING,
                                                   to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='references')),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AddField(
            model_name='jobs',
            name='references',
            field=models.ManyToManyField(to='jobs.references'),
        ),
    ]
