# Generated by Django 4.0.3 on 2022-04-15 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobs_references_delete_test_jobs_references'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='delivery_due',
            new_name='delivery_time',
        ),
    ]
