# Generated by Django 4.0.3 on 2022-04-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_rename_delivery_due_jobs_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='category',
            field=models.CharField(choices=[('D', 'Design'), ('VE', 'Video Editing')], default='D', max_length=2),
        ),
    ]
