# Generated by Django 4.0.3 on 2022-04-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_jobs_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='final_file',
            field=models.FileField(null=True, upload_to='', blank=True),
        ),
    ]
