# Generated by Django 4.0.3 on 2022-04-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_jobs_final_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='status',
            field=models.CharField(choices=[('C', 'Creating'), ('WA', 'Waiting Approval'), ('F', 'Finished')], default='C', max_length=2),
        ),
    ]
