# Generated by Django 4.0.3 on 2022-04-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_jobs_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='final_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
