# Generated by Django 4.0.3 on 2022-04-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_jobs_final_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='final_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
